// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/lexis-project/lexis-backend-services-userorg-service.git/client/access_management"
	"github.com/lexis-project/lexis-backend-services-userorg-service.git/client/hpc_management"
	"github.com/lexis-project/lexis-backend-services-userorg-service.git/client/organization_management"
	"github.com/lexis-project/lexis-backend-services-userorg-service.git/client/project_management"
	"github.com/lexis-project/lexis-backend-services-userorg-service.git/client/status_management"
	"github.com/lexis-project/lexis-backend-services-userorg-service.git/client/user_management"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8000"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v0.3"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new user organization API HTTP client.
func New(c Config) *UserOrganizationAPI {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(UserOrganizationAPI)
	cli.Transport = transport
	cli.AccessManagement = access_management.New(transport, strfmt.Default, c.AuthInfo)
	cli.HpcManagement = hpc_management.New(transport, strfmt.Default, c.AuthInfo)
	cli.OrganizationManagement = organization_management.New(transport, strfmt.Default, c.AuthInfo)
	cli.ProjectManagement = project_management.New(transport, strfmt.Default, c.AuthInfo)
	cli.StatusManagement = status_management.New(transport, strfmt.Default, c.AuthInfo)
	cli.UserManagement = user_management.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// UserOrganizationAPI is a client for user organization API
type UserOrganizationAPI struct {
	AccessManagement       *access_management.Client
	HpcManagement          *hpc_management.Client
	OrganizationManagement *organization_management.Client
	ProjectManagement      *project_management.Client
	StatusManagement       *status_management.Client
	UserManagement         *user_management.Client
	Transport              runtime.ClientTransport
}
