// Code generated by go-swagger; DO NOT EDIT.

package status_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ShowStatusHandlerFunc turns a function with the right signature into a show status handler
type ShowStatusHandlerFunc func(ShowStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ShowStatusHandlerFunc) Handle(params ShowStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ShowStatusHandler interface for that can handle valid show status params
type ShowStatusHandler interface {
	Handle(ShowStatusParams, interface{}) middleware.Responder
}

// NewShowStatus creates a new http.Handler for the show status operation
func NewShowStatus(ctx *middleware.Context, handler ShowStatusHandler) *ShowStatus {
	return &ShowStatus{Context: ctx, Handler: handler}
}

/*ShowStatus swagger:route GET /status statusManagement showStatus

Basic status of the system

*/
type ShowStatus struct {
	Context *middleware.Context
	Handler ShowStatusHandler
}

func (o *ShowStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShowStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
