// Code generated by go-swagger; DO NOT EDIT.

package status_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewShowStatusParams creates a new ShowStatusParams object
// no default values defined in spec.
func NewShowStatusParams() ShowStatusParams {

	return ShowStatusParams{}
}

// ShowStatusParams contains all the bound params for the show status operation
// typically these are obtained from a http.Request
//
// swagger:parameters showStatus
type ShowStatusParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewShowStatusParams() beforehand.
func (o *ShowStatusParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
