// Code generated by go-swagger; DO NOT EDIT.

// Package restapi User-Organization API
//
//  An API which supports management of customers and organizations within the LEXIS portal; this version is intended for use in LEXIS Portal R1
//  Schemes:
//    http
//    https
//  Host: localhost:8000
//  BasePath: /api/v0.3
//  Version: 0.3.2021-12-15
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <diego@cyclops-labs.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
