// Code generated by go-swagger; DO NOT EDIT.

package status_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShowStatusParams creates a new ShowStatusParams object
// with the default values initialized.
func NewShowStatusParams() *ShowStatusParams {

	return &ShowStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowStatusParamsWithTimeout creates a new ShowStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowStatusParamsWithTimeout(timeout time.Duration) *ShowStatusParams {

	return &ShowStatusParams{

		timeout: timeout,
	}
}

// NewShowStatusParamsWithContext creates a new ShowStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowStatusParamsWithContext(ctx context.Context) *ShowStatusParams {

	return &ShowStatusParams{

		Context: ctx,
	}
}

// NewShowStatusParamsWithHTTPClient creates a new ShowStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowStatusParamsWithHTTPClient(client *http.Client) *ShowStatusParams {

	return &ShowStatusParams{
		HTTPClient: client,
	}
}

/*ShowStatusParams contains all the parameters to send to the API endpoint
for the show status operation typically these are written to a http.Request
*/
type ShowStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show status params
func (o *ShowStatusParams) WithTimeout(timeout time.Duration) *ShowStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show status params
func (o *ShowStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show status params
func (o *ShowStatusParams) WithContext(ctx context.Context) *ShowStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show status params
func (o *ShowStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show status params
func (o *ShowStatusParams) WithHTTPClient(client *http.Client) *ShowStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show status params
func (o *ShowStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ShowStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
