// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreatedResponse created response
//
// swagger:model CreatedResponse
type CreatedResponse struct {

	// ID
	ID string `json:"ID,omitempty"`

	// link
	Link string `json:"Link,omitempty"`
}

// Validate validates this created response
func (m *CreatedResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreatedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatedResponse) UnmarshalBinary(b []byte) error {
	var res CreatedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
